<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bagian extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Bagian_model');
        $this->load->model('Setting_app_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);
        $bagian = $this->Bagian_model->get_all();
        $data = array(
            'bagian_data' => $bagian,
            'sett_apps' => $this->Setting_app_model->get_by_id(1),
            'classnyak' => $this
        );
        $this->template->load('template','bagian/bagian_wrapper', $data);
    }

    public function list()
    {
        is_allowed($this->uri->segment(1),null);
        $bagian = $this->Bagian_model->get_all();
        $data = array(
            'bagian_data' => $bagian,
        );
        $this->load->view('bagian/bagian_list', $data);
    }

    public function read() 
    {
        is_allowed($this->uri->segment(1),'read');
        $id = $this->input->post('id');
        $row = $this->Bagian_model->get_by_id(decrypt_url($id));
        if ($row) {
            $data = array(
        		'id_bagian' => $row->id_bagian,
        		'nama_bagian' => $row->nama_bagian,
                'sett_apps' => $this->Setting_app_model->get_by_id(1),
	       );
            $this->load->view('bagian/bagian_read', $data);
        } else {
            echo 'not found';
        }
    }

    public function create() 
    {
        is_allowed($this->uri->segment(1),'create');
        $data = array(
            'button' => 'Create',
            'action' => 'form_create_action',
    	    'id_bagian' => set_value('id_bagian'),
    	    'nama_bagian' => set_value('nama_bagian'),
            'sett_apps' => $this->Setting_app_model->get_by_id(1),
    	);
        $this->load->view('bagian/bagian_form', $data);
    }
    
    public function create_action() 
    {
        is_allowed($this->uri->segment(1),'create');

        $data = array(
            'nama_bagian' => $this->input->post('nama_bagian',TRUE),
        );

        $this->Bagian_model->insert($data);
        $this->list();
        
    }
    
    public function update() 
    {
        is_allowed($this->uri->segment(1),'update');
        $id = $this->input->post('id');
        $row = $this->Bagian_model->get_by_id(decrypt_url($id));

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => 'form_update_action',
		'id_bagian' => set_value('id_bagian', $row->id_bagian),
		'nama_bagian' => set_value('nama_bagian', $row->nama_bagian),
        'sett_apps' => $this->Setting_app_model->get_by_id(1),
	    );
            $this->load->view('bagian/bagian_form', $data);
        } else {
            echo 'not found';
        }
    }
    
    public function update_action() 
    {
        is_allowed($this->uri->segment(1),'update');

            $data = array(
		'nama_bagian' => $this->input->post('nama_bagian',TRUE),
	    );

            $this->Bagian_model->update($this->input->post('id_bagian', TRUE), $data);
        $this->list();
        
    }
    
    public function delete() 
    {
        is_allowed($this->uri->segment(1),'delete');
        $id = $this->input->post('id');
        $row = $this->Bagian_model->get_by_id(decrypt_url($id));

        if ($row) {
            $this->Bagian_model->delete(decrypt_url($id));
            $this->list();
        } else {
            echo 'not found';
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_bagian', 'nama bagian', 'trim|required');

	$this->form_validation->set_rules('id_bagian', 'id_bagian', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Bagian.php */
/* Location: ./application/controllers/Bagian.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-29 10:24:47 */
/* http://harviacode.com */