<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_material extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Jenis_material_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);
        $jenis_material = $this->Jenis_material_model->get_all();
        $data = array(
            'jenis_material_data' => $jenis_material,
        );
        $this->template->load('template','jenis_material/jenis_material_list', $data);
    }

    public function read($id) 
    {
        is_allowed($this->uri->segment(1),'read');
        $row = $this->Jenis_material_model->get_by_id(decrypt_url($id));
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nama_jenis_material' => $row->nama_jenis_material,
	    );
            $this->template->load('template','jenis_material/jenis_material_read', $data);
        } else {
            $this->session->set_flashdata('error', 'Record Not Found');
            redirect(site_url('jenis_material'));
        }
    }

    public function create() 
    {
        is_allowed($this->uri->segment(1),'create');
        $data = array(
            'button' => 'Create',
            'action' => site_url('jenis_material/create_action'),
	    'id' => set_value('id'),
	    'nama_jenis_material' => set_value('nama_jenis_material'),
	);
        $this->template->load('template','jenis_material/jenis_material_form', $data);
    }
    
    public function create_action() 
    {
        is_allowed($this->uri->segment(1),'create');
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_jenis_material' => $this->input->post('nama_jenis_material',TRUE),
	    );

            $this->Jenis_material_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jenis_material'));
        }
    }
    
    public function update($id) 
    {
        is_allowed($this->uri->segment(1),'update');
        $row = $this->Jenis_material_model->get_by_id(decrypt_url($id));

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jenis_material/update_action'),
		'id' => set_value('id', $row->id),
		'nama_jenis_material' => set_value('nama_jenis_material', $row->nama_jenis_material),
	    );
            $this->template->load('template','jenis_material/jenis_material_form', $data);
        } else {
            $this->session->set_flashdata('error', 'Record Not Found');
            redirect(site_url('jenis_material'));
        }
    }
    
    public function update_action() 
    {
        is_allowed($this->uri->segment(1),'update');
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nama_jenis_material' => $this->input->post('nama_jenis_material',TRUE),
	    );

            $this->Jenis_material_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jenis_material'));
        }
    }
    
    public function delete($id) 
    {
        is_allowed($this->uri->segment(1),'delete');
        $row = $this->Jenis_material_model->get_by_id(decrypt_url($id));

        if ($row) {
            $this->Jenis_material_model->delete(decrypt_url($id));
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jenis_material'));
        } else {
            $this->session->set_flashdata('error', 'Record Not Found');
            redirect(site_url('jenis_material'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_jenis_material', 'nama jenis material', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jenis_material.php */
/* Location: ./application/controllers/Jenis_material.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-05 10:30:26 */
/* http://harviacode.com */