<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dokumen_model extends CI_Model
{

    public $table = 'dokumen';
    public $id = 'dokumen_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('dokumen_id', $q);
	$this->db->or_like('nama_dokumen', $q);
	$this->db->or_like('tgl_pembuatan', $q);
	$this->db->or_like('tgl_expired', $q);
	$this->db->or_like('tempat_pembuatan', $q);
	$this->db->or_like('berkas_dokumen', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dokumen_model.php */
/* Location: ./application/models/Dokumen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-06 06:28:54 */
/* http://harviacode.com */