<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Item_model extends CI_Model
{

    public $table = 'item';
    public $id = 'item_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kategori', 'kategori.kategori_id = item.kategori_id', 'left');
        $this->db->join('unit', 'unit.unit_id = item.unit_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('item_id', $q);
	$this->db->or_like('kd_internal_item', $q);
	$this->db->or_like('kd_external_item', $q);
	$this->db->or_like('nama_item', $q);
	$this->db->or_like('kategori_id', $q);
	$this->db->or_like('unit_id', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('can_be_sold', $q);
	$this->db->or_like('can_be_purchased', $q);
	$this->db->or_like('estimasi_harga', $q);
	$this->db->or_like('stok', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function buat_kode()   {
        $this->db->select('RIGHT(item.kd_internal_item,4) as kode', FALSE);
        $this->db->order_by('kd_internal_item','DESC');
        // $this->db->where('vessel_id',$vessel_id);    
        $this->db->limit(1);    
        $query = $this->db->get('item');      //cek dulu apakah ada sudah ada kode di tabel.    
        if($query->num_rows() <> 0){      
           //jika kode ternyata sudah ada.      
        $data = $query->row();      
        $kode = intval($data->kode) + 1;    
        }
        else {      
           //jika kode belum ada      
        $kode = 1;    
        }
        $kodemax = str_pad($kode, 6, "IT000", STR_PAD_LEFT); // angka 4 menunjukkan jumlah digit angka 0
        $kodejadi = "".$kodemax;    // hasilnya ODJ-9921-0001 dst.
        return $kodejadi; 
    }

}

/* End of file Item_model.php */
/* Location: ./application/models/Item_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-24 18:34:07 */
/* http://harviacode.com */