<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Karyawan_model extends CI_Model
{

    public $table = 'karyawan';
    public $id = 'karyawan_id';
    public $table2 = 'berkas';
    public $id2 = 'berkas_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('jabatan', 'jabatan.jabatan_id = karyawan.jabatan_id', 'left');
        $this->db->join('divisi', 'divisi.divisi_id = karyawan.divisi_id', 'left');
        $this->db->join('status_karyawan', 'status_karyawan.status_karyawan_id = karyawan.status_karyawan_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_berkas ($id){
        $this->db->select('berkas.*');
        $this->db->from('berkas');
        $this->db->where('karyawan_id', $id);
        $query = $this->db->get();
        return $query;
    }

    function get_berkas_by_id($id)
    {
        $this->db->where($this->id2, $id);
        return $this->db->get($this->table2)->row();
    }

    function delete_berkas($id_berkas)
    {
        $this->db->where($this->id2, $id_berkas);
        $this->db->delete($this->table2);
    }
    

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('divisi', 'divisi.divisi_id = karyawan.divisi_id','left');
        $this->db->join('jabatan', 'jabatan.jabatan_id = karyawan.jabatan_id', 'left');
        $this->db->join('status_karyawan', 'status_karyawan.status_karyawan_id = karyawan.status_karyawan_id', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('karyawan_id', $q);
	$this->db->or_like('nama_karyawan', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('jabatan_id', $q);
	$this->db->or_like('status_karyawan_id', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('status_kawin', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('photo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Karyawan_model.php */
/* Location: ./application/models/Karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-23 06:09:20 */
/* http://harviacode.com */