<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_menu_model extends CI_Model
{

    public $table = 'sub_menu';
    public $id = 'sub_menu_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('menu', 'menu.menu_id = sub_menu.menu_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('sub_menu_id', $q);
	$this->db->or_like('menu_id', $q);
	$this->db->or_like('nama_sub_menu', $q);
	$this->db->or_like('url', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sub_menu_model.php */
/* Location: ./application/models/Sub_menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-21 06:23:00 */
/* http://harviacode.com */